name: ESLint Code Analysis

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: lab09/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        working-directory: lab09    
        run: npm install

      - name: Create reports directory
        working-directory: lab09
        run: mkdir -p reports

      - name: Install ESLint SARIF Formatter
        working-directory: lab09
        run: npm install @microsoft/eslint-formatter-sarif --save-dev

      - name: Run ESLint with SARIF output
        working-directory: lab09
        run: npx eslint . --format @microsoft/eslint-formatter-sarif --output-file reports/eslint-results.sarif || true

      - name: Debug ESLint Output
        working-directory: lab09 
        run: cat reports/eslint-results.sarif || echo "No SARIF report generated"

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lab09/reports/eslint-results.sarif